### ISSUE TITLE
Error when launching chaostrainer on ubuntu

### ISSUE THREAD

**Issue by Pinkcommando** [schematical/chaostrainer-public#4]
Version: 0.0.1
OS: Ubuntu

`
Unable to preload the following plugins:
	ScreenSelector.so
Display 0 '0': 1920x1080 (primary device).
Logging to /home/USER/.config/unity3d/Schematical/ChaosTrainer/Player.log
`

**Comment by schematical** [comment]
Oh good find. Can you upload Player.log here? @Pinkcommando

**Comment by Pinkcommando** [comment]
[Player.log](https://github.com/schematical/chaostrainer-public/files/2439304/Player.log)

**Comment by schematical** [comment]
Interesting:
```
The referenced script on this Behaviour (Game Object 'BotBreedingButton') is missing!
```
I found it in the backend. The script was added twice but one of the scripts lost its corresponding C# script. None of the other OSs seemed to care except for linux. 

Pushing new build now...

**Comment by schematical** [comment]
_NOTE: Half this issue was discussed in discord so I am copying that info over to here now that it was resolved_

Looking at that Player.log:
```
UnloadTime: 1.730000 ms
Persistant Data Dir: /home/vincent/.config/unity3d/Schematical/ChaosTrainer

(Filename: ./Runtime/Export/Debug.bindings.h Line: 43)

Atempting to load chaosTrainer.json: /home/vincent/.config/unity3d/Schematical/ChaosTrainer/save_data/chaos_trainer.json

(Filename: ./Runtime/Export/Debug.bindings.h Line: 43)

Successfully Loaded Existing: chaos_trainer.json
```
The files are being created and loading just fine.
But this line seems to be the issue:
```
Error loading /home/vincent/chaostrainer-public-master/ChaosTrainerLinux_Data/Plugins/x86/ScreenSelector.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

After some googling and considering the other guys tried it on Linux and seems to be able to make it work this might be the solution:

https://www.linuxquestions.org/questions/linux-software-2/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0-a-921435/
